//
// ThorCostmatrix.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
    import AnyCodable
#endif

public struct ThorCostmatrix: Codable, Hashable {
    public var allowSecondPass: Bool? = false
    public var checkReverseConnection: Bool? = true
    public var heirarchyLimits: HeirarchyLimits?
    public var maxInterations: Int? = 2800
    public var maxReservedLocations: Int? = 25
    public var minIterations: Int? = 100

    public init(allowSecondPass: Bool? = false, checkReverseConnection: Bool? = true, heirarchyLimits: HeirarchyLimits? = nil, maxInterations: Int? = 2800, maxReservedLocations: Int? = 25, minIterations: Int? = 100) {
        self.allowSecondPass = allowSecondPass
        self.checkReverseConnection = checkReverseConnection
        self.heirarchyLimits = heirarchyLimits
        self.maxInterations = maxInterations
        self.maxReservedLocations = maxReservedLocations
        self.minIterations = minIterations
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case allowSecondPass = "allow_second_pass"
        case checkReverseConnection = "check_reverse_connection"
        case heirarchyLimits = "heirarchy_limits"
        case maxInterations = "max_interations"
        case maxReservedLocations = "max_reserved_locations"
        case minIterations = "min_iterations"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(allowSecondPass, forKey: .allowSecondPass)
        try container.encodeIfPresent(checkReverseConnection, forKey: .checkReverseConnection)
        try container.encodeIfPresent(heirarchyLimits, forKey: .heirarchyLimits)
        try container.encodeIfPresent(maxInterations, forKey: .maxInterations)
        try container.encodeIfPresent(maxReservedLocations, forKey: .maxReservedLocations)
        try container.encodeIfPresent(minIterations, forKey: .minIterations)
    }
}
