name: Release

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      bump_version_scheme:
        type: choice
        description: "Bump version scheme"
        required: true
        default: "patch"
        options:
          - "patch"
          - "minor"
          - "major"

jobs:
  release-on-push:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: rymndhng/release-on-push-action@v0.28.0
        with:
          bump_version_scheme: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' && 'patch' || inputs.bump_version_scheme }}
